### ISSUE TITLE
Instalation de l'agent

### ISSUE THREAD

**Issue by BrunoDefrance** [dalibo/temboard-agent#130]
Bonjour
Je report !
```
root@servsig2:/usr/local/share/temboard-agent/quickstart# sudo -u postgres temboard-agent -c /usr/local/share/temboard-agent/quickstart/temboard-agent.conf

ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/cli.py", line 47, in cli_wrapper
ERROR:     retcode = main(argv, environ) or 1
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/scripts/agent.py", line 103, in main
ERROR:     args=args, environ=environ,
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/configuration.py", line 149, in load_configuration
ERROR:     config.load(args=args, environ=environ)
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/configuration.py", line 264, in load
ERROR:     self.add_values(iter_defaults(self.specs))
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/configuration.py", line 236, in add_values
ERROR:     value = spec.validate(value)
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/configuration.py", line 127, in validate
ERROR:     return self.validator(value.value)
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/validators.py", line 104, in writeabledir
ERROR:     raise ValueError('Not writable')
ERROR: ValueError: Not writable
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard-agent/issues! Thanks!
```

... mais de rien !

mon .conf

```
[temboard]
# Bind port.
port = 2345
# Bind address.
address = 172.21.254.93
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity"]
# SSL: certificat file path (.pem)
ssl_cert_file = temboard-agent_CHANGEME.pem
# SSL: private key file path (.key)
ssl_key_file = temboard-agent_CHANGEME.key
# Hostname must be an unique and valid FQDN : e.g. db1.mydomain.foo
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
# hostname = db1.mydomain.foo
# Key
key = SECRETKEYTOBECHANGED

[postgresql]
# Unix socket path.
host = /var/run/postgresql
# PG port number.
port = 5432
# Super-user name.
user = postgres
# Super-user password.
password = #####
# Default database.
dbname = postgres
# Instance name.
instance = main

[logging]
# Available methods for logging: stderr, syslog or file
method = stderr
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux system.
# When using file logging method, this is referencing the log file path.
# destination = /var/log/temboard-agent/temboard-agent.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = DEBUG
```

Merci
Bruno Defrance

**Comment by bersace** [comment]
@BrunoDefrance ok, il y a un dossier où `postgres` ne peut pas écrire. Faut corriger l'erreur pour remonter de quel dossier il s'agit. Je pense que c'est le `HOME`. Essaie de faire un `cd ~postgres` avant ou utilise `sudo -i -u postgres`.

**Comment by BrunoDefrance** [comment]
merci !

J'ai une autre erreur ... la version ? 9.6 ...

```
ERROR: 28000
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/pluginsmgmt.py", line 38, in load_plugins_configurations
ERROR:     conn.connect()
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/spc.py", line 845, in connect
ERROR:     self._check_message_error(message)
ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/spc.py", line 702, in _check_message_error
ERROR:     raise error(code, typ, msg)
ERROR: error: 28000
ERROR: Not able to get PostgreSQL version number.
```

**Comment by julmon** [comment]
Hi,

It seems that the agent can not connect to postgres instance. Could you please check parameters of `[postgres]` section : `host`, `port` and `password` ?

Regards,

**Comment by BrunoDefrance** [comment]
Hi,
Exact !
Confusion avec l'utilisateur créé dans la base de teamboard avec celui créé dans la base de l'agent (celle à superviser).
Sorry ...
thank you

**Comment by julmon** [comment]
You're welcome.
