### ISSUE TITLE
Invalid FQDN when running with docker

### ISSUE THREAD

**Issue by pgiraud** [dalibo/temboard-agent#151]
When running temboard-agent inside a docker container as described in the [contributing doc](https://github.com/dalibo/temboard-agent/blob/master/doc/contributing.rst), I now get the following error:
```
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/plugins/dashboard/__init__.py", line 836, in dashboard_collector_worker
ERROR:     data = metrics.get_metrics(conn, config_nt)
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/plugins/dashboard/metrics.py", line 27, in get_metrics
ERROR:     'hostname': sysinfo.hostname(config.temboard['hostname']),
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/inventory.py", line 31, in hostname
ERROR:     raise ValueError("Invalid FQDN: %s" % (hostname))
ERROR: ValueError: Invalid FQDN: b02142c0747c
```

It looks like temboard expects the hostname to contain dots.

**Comment by pgiraud** [comment]
Sorry to reopen issue. The FQDN issue is fixed but now we get the following error:

```
ERROR: 'getpwuid(): uid not found: 70'
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/plugins/monitoring/__init__.py", line 976, in monitoring_collector_worker
ERROR:     instances.append(instance_info(conninfo, system_info['hostname']))
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/plugins/monitoring/inventory.py", line 92, in instance_info
ERROR:     instance_info['sysuser'] = pwd.getpwuid(statinfo.st_uid).pw_name
ERROR: KeyError: 'getpwuid(): uid not found: 70'
ERROR: Could not collect data
```
