### ISSUE TITLE
dockerised agent

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard-agent#211]
Hello, i try to register a dockerised agent, i get this error in the dockerised UI: 
```
 INFO: Getting discovery.
ERROR: <urlopen error [Errno 111] Connection refused>
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/lib/python2.7/site-packages/temboardui/handlers/settings/instance.py", line 345, in get_discover
ERROR:     self.ssl_ca_cert_file, agent_address, agent_port)
ERROR:   File "/usr/local/lib/python2.7/site-packages/temboardui/temboardclient.py", line 401, in temboard_discover
ERROR:     raise TemboardError(500, str(e))
ERROR: TemboardError: <urlopen error [Errno 111] Connection refused>
 INFO: Failed.

```
Any idea ?
thx

**Comment by bersace** [comment]
Hi @pmpetit this mean the UI can't connect to the agent. Please check agent address and port.

**Comment by bersace** [comment]
@pmpetit Is this issue still relevant ? Actually, it looks like an UI error, not agent.

**Comment by pmpetit** [comment]
Hello, you can close
Thanks
