### ISSUE TITLE
Install is broken from master.zip

### ISSUE THREAD

**Issue by bersace** [dalibo/temboard-agent#25]
Just run `make -C docker clean build`:

``` console
 ---> Running in 5285f46166f4                                                                                                                         
Collecting https://github.com/dalibo/temboard-agent/archive/master.zip                                                                                
  Downloading https://github.com/dalibo/temboard-agent/archive/master.zip                                                                             
    Complete output from command python setup.py egg_info:                                                                                            
    Traceback (most recent call last):                                                                                                                
      File "<string>", line 1, in <module>                                                                                                            
      File "/tmp/pip-8hp1s5-build/setup.py", line 9, in <module>
        subprocess.check_output(["git", "describe", "--tags"])
      File "/usr/local/lib/python2.7/subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)                  
      File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
                                            
    ----------------------------------------    
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-8hp1s5-build/
The command '/bin/sh -c pip install --no-cache-dir https://github.com/dalibo/temboard-agent/archive/master.zip' returned a non-zero code: 1
Makefile:4 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 1                                         
make : on quitte le répertoire « /home/bersace/src/dalibo/temboard-agent-dev/docker »
```

**Comment by bersace** [comment]
Fixed by #27
