### ISSUE TITLE
Cannot send data to collector

### ISSUE THREAD

**Issue by Rodac** [dalibo/temboard-agent#304]
After updating temboard-agent 2.0 to 2.2, I have issues seeing data on home page of temboard.
In the logs of temboard-agent, I can see this error :

```shell
2018-12-19 13:56:45,882 temboardagent[46863]: [monitoring] ERROR: Failed to send data to collector: 
2018-12-19 13:56:45,882 temboardagent[46863]: [monitoring] ERROR: You should find details in temBoard UI logs.
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR: Failed to send data to collector.
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR: Traceback (most recent call last):
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/taskmanager.py", line 815, in exec_worker
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 102, in wrapper
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 227, in monitoring_sender_worker
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR:     raise Exception("Failed to send data to collector.")
2018-12-19 13:56:45,883 temboardagent[46863]: [taskmanager] ERROR: Exception: Failed to send data to collector.
2018-12-19 13:56:45,904 temboardagent[46410]: [taskmanager] DEBUG: Job monitoring_sender is dead
2018-12-19 13:56:45,905 temboardagent[46410]: [taskmanager] DEBUG: Job output : {'content': Exception('Failed to send data to collector.',), 'type': (6,)}
2018-12-19 13:56:45,905 temboardagent[46411]: [taskmanager] DEBUG: Received Message={'content': {'status': 32, 'output': Exception('Failed to send data to collector.',), 'stop_datetime': datetime.datetime(2018, 12, 19, 12, 56, 45, 905228), 'task_id': 'monitoring_sender'}, 'type': 1}
`

Running on CentOS 7.6, with the RPM installation. (version 2.2.2)
Python 2.7.5
Setuptools 0.9.8


Any idea of what's going wrong ?

**Comment by julmon** [comment]
Do you see something new in temboard UI logs ?

**Comment by Rodac** [comment]
I have this kind of error messages :

```shell
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR: [Errno 2] No such file or directory
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR: Traceback (most recent call last):
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 140, in push_data
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:     expire=0,
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/scheduler/taskmanager.py", line 122, in schedule_task
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:     authkey=authkey
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/scheduler/taskmanager.py", line 345, in send_message
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:     conn = Client(address, authkey=authkey)
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:   File "/usr/lib64/python2.7/multiprocessing/connection.py", line 173, in Client
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:     c = SocketClient(address)
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:   File "/usr/lib64/python2.7/multiprocessing/connection.py", line 308, in SocketClient
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:     s.connect(address)
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:   File "/usr/lib64/python2.7/socket.py", line 224, in meth
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR:     return getattr(self._sock,name)(*args)
2018-12-19 14:37:45,747 temboard-agent[38455]: [temboardui] ERROR: error: [Errno 2] No such file or directory
`

**Comment by julmon** [comment]
Could you try to restart your temboard UI please and take a look at its logs ?
It seems that the task scheduler of you temboard UI have an issue  with its local socket.

**Comment by Rodac** [comment]
Thank you @julmon, restarting (by first killing temboard processes) resolved the problem.
I'm updating every agent to make it communicate again.
