### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by ChristophBerg** [dalibo/temboard-agent#330]
I don't yet know what's wrong, but this looks like temboard choking while printing some error message:
```
# LC_ALL=C temboard-agent -c temboard-agent.conf -d
 INFO: Found plugin monitoring = temboardagent.plugins.monitoring:MonitoringPlugin.
 INFO: Found plugin dashboard = temboardagent.plugins.dashboard:DashboardPlugin.
 INFO: Found plugin pgconf = temboardagent.plugins.pgconf:PgConfPlugin.
 INFO: Found plugin administration = temboardagent.plugins.administration:AdministrationPlugin.
 INFO: Found plugin activity = temboardagent.plugins.activity:ActivityPlugin.
 INFO: Found plugin maintenance = temboardagent.plugins.maintenance:MaintenancePlugin.
 INFO: Loading plugin monitoring.
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 256, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/scripts/agent.py", line 96, in main
ERROR:     self.bootstrap(args=args, environ=environ)
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 99, in bootstrap
ERROR:     self.apply_config()
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/cli.py", line 50, in apply_config
ERROR:     return super(Application, self).apply_config()
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 151, in apply_config
ERROR:     self.update_plugins(old_plugins=old_plugins)
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 218, in update_plugins
ERROR:     self.plugins[name].load()
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 293, in load
ERROR:     pg_version = self.app.postgres.fetch_version()
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/postgres.py", line 54, in fetch_version
ERROR:     with self.connect() as conn:
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/postgres.py", line 23, in __enter__
ERROR:     self.conn.connect()
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/spc.py", line 817, in connect
ERROR:     self._check_message_error(messages[0])
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/spc.py", line 698, in _check_message_error
ERROR:     msg = err_split[3][1:].decode()
ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)
ERROR: temboardagent version is 3.0.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!
```
Version: 3.0-0dlb1stretch1

**Comment by ChristophBerg** [comment]
message is `('E', {'type': u'S', 'string': 'FATAL\x00VFATAL\x00C28000\x00MPeer-Authentifizierung f\xc3\xbcr Benutzer \xc2\xbbpostgres\xc2\xab fehlgeschlagen\x00Fauth.c\x00L336\x00Rauth_failed\x00\x00'})`, so it's choking on the German `ü`

**Comment by bersace** [comment]
@ChristophBerg it looks like your python is misconfigured:

``` console
$ LANG=C LC_ALL=C python -c 'print(b"\xc2\xab".decode())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\xab' in position 0: ordinal not in range(128)
$ LANG=C.UTF-8 LC_ALL=C.UTF-8 python -c 'print(b"\xc2\xab".decode())'
«
$
```

**Comment by bersace** [comment]
@ChristophBerg you could work around this by ensuring python locales is UTF-8, like Postgres. But, python2 is not easy to configure properly. I'm digging.

**Comment by ChristophBerg** [comment]
It was failing the same way when running without LC_ALL, with proper LANG=de_DE.utf8. I also tried LC_ALL=C.UTF-8 and it still complained about the 'ascii' codec.

**Comment by julmon** [comment]
Hello,

We found a way to fix this properly and are working on it.

**Comment by julmon** [comment]
Hello,

Version 3.1 has been released and should fix this. Please let us know if it's not.

Thank you !
