### ISSUE TITLE
Running agent in debug mode

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard-agent#345]
Hello, following the steps : 
https://github.com/dalibo/temboard/blob/master/CONTRIBUTING.md

i have this error, while running "sudo -u postgres temboard-agent"
```
    ~/gitHome/temboard/temboard    master   8 docker-ccompose exec agent bash                                                                   ✔  13:44:09  🐳 root@c1d96ad8d1b9:/var/lib/temboard-agent#  pip install -e /usr/local/src/temboard-agent/
Obtaining file:///usr/local/src/temboard-agent
Installing collected packages: temboard-agent
  Found existing installation: temboard-agent 4.0+master
    Uninstalling temboard-agent-4.0+master:
      Successfully uninstalled temboard-agent-4.0+master
  Running setup.py develop for temboard-agent
Successfully installed temboard-agent
root@c1d96ad8d1b9:/var/lib/temboard-agent# sudo -u postgres temboard-agent
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/temboard-agent/temboardagent/scripts/agent.py", line 10, in <module>
    from ..toolkit import taskmanager
ImportError: cannot import name 'taskmanager' from 'temboardagent.toolkit' (unknown location)
root@c1d96ad8d1b9:/var/lib/temboard-agent#
```

**Comment by bersace** [comment]
It looks like you're missing toolkit submodule. Run `git submodule update --init` to fix that. Does it fixes this error ?

**Comment by bersace** [comment]
We should update documentation. Please keep this issue opened.

**Comment by pmpetit** [comment]
i have forgotten the -recursive option...
