### ISSUE TITLE
temboard-agent-register crashes on accented character in a comment in temboard-agent.conf 

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard-agent#356]
Adding a é,è,à in a comment in temboard-agent.conf or auto.conf gives an error when registering:

This works:
```
root@pegase:/etc/temboard-agent# rgrep port 
11/pagode/temboard-agent.conf.d/auto.conf:port = 65113
11/pagode/temboard-agent.conf.d/auto.conf:port = 11003
11/pagode/temboard-agent.conf:# Bind port.
11/pagode/temboard-agent.conf:# port ignore
11/pagode/temboard-agent.conf:port = 666
11/pagode/temboard-agent.conf:# PG port number.
11/pagode/temboard-agent.conf:port = 5432

root@pegase:/etc/temboard-agent# sudo -u postgres temboard-agent-register -c /etc/temboard-agent/11/pagode/temboard-agent.conf  --host pegase.dalibo.net --port=65113  --groups default https://localhost:3001
Getting system & PostgreSQL informations from the agent (https://pegase.dalibo.net:65113/discover) ...
Login at https://localhost:3001 ...
 Username: 
...
```

One é in a comment, and it crashes:
```
root@pegase:/etc/temboard-agent# rgrep port 
11/pagode/temboard-agent.conf.d/auto.conf:port = 65113
11/pagode/temboard-agent.conf.d/auto.conf:port = 11003
11/pagode/temboard-agent.conf:# Bind port.
11/pagode/temboard-agent.conf:# port ignoré
11/pagode/temboard-agent.conf:port = 666
11/pagode/temboard-agent.conf:# PG port number.
11/pagode/temboard-agent.conf:port = 5432

root@pegase:/etc/temboard-agent# vi 11/pagode/temboard-agent.conf*
2 fichiers à éditer
root@pegase:/etc/temboard-agent# sudo -u postgres temboard-agent-register -c /etc/temboard-agent/11/pagode/temboard-agent.conf  --host pegase.dalibo.net --port=65113  --groups default https://localhost:3001
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 256, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/scripts/register.py", line 111, in main
ERROR:     self.bootstrap(args=args, environ=environ)
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 89, in bootstrap
ERROR:     self.read_file(parser, configfile)
ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/app.py", line 157, in read_file
ERROR:     parser.readfp(fp)
ERROR:   File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 769, in readfp
ERROR:     self.read_file(fp, source=filename)
ERROR:   File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 724, in read_file
ERROR:     self._read(f, source)
ERROR:   File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1052, in _read
ERROR:     if line.strip().startswith(prefix):
ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
ERROR: temboardagent version is 4.1.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!

```

Config : my laptop, Ubuntu 18.04.3 LTS

**Comment by Krysztophe** [comment]
BTW, there is the same problem in temboard itself with an é in `temboard.conf` :

```
sept. 27 17:09:58 pegase env[6357]: ERROR:   File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line
sept. 27 17:09:58 pegase env[6357]: ERROR:     self._read(f, source)
sept. 27 17:09:58 pegase env[6357]: ERROR:   File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line
sept. 27 17:09:58 pegase env[6357]: ERROR:     if line.strip().startswith(prefix):
sept. 27 17:09:58 pegase env[6357]: ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal no
sept. 27 17:09:58 pegase env[6357]: ERROR: temboardui version is 4.1.
sept. 27 17:09:58 pegase env[6357]: ERROR: This is a bug!
sept. 27 17:09:58 pegase env[6357]: ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```
