### ISSUE TITLE
ERROR: ValueError: address type of u'/var/lib/temboard/.tm.socket' unrecognized

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard-agent#358]
I get this error regularly in temboard.log and temboard_agent.log (see below). The temboard interface works well, except for the monitoring (doesn't show any data).

The problem disappears when I remove `[monitoring]` from `plugins` in `temboard-agent.conf`. I've tried to reduce `probes` to a single value (`cpu` or `wal_files`) or `dbnames` to `postgres`, without luck. 

This seems instance-independant, I have 3 agents on this host, and they all had this problem from the beginning.

Everything is well on another server with temboard & different instances, and I can't find a difference. 

Config: 4.1 with Debian packages, and auto_configure scripts.

temboard.conf:
```
home=/var/lib/temboard
```

temboard.log : 
```
2019-09-28 12:04:59,282 temboardui[28103]: [monitoring] WARNING: Failed to preprocess alerting check 'btree_bloat'                                           
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR: Unhandled Error:                                                                                                           
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR: Traceback (most recent call last):                                                                                         
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 224, in error_middleware                    
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     return func(request, *args)                                                                                            
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 379, in json_middleware                     
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     return func(request, *args)                                                                                            
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 419, in user_middleware                     
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     return func(request, *args)                                                                                            
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 142, in collector
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     expire=0,                                                                                                              
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 787, in schedule_task       
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     conn = Client(self.scheduler.address, self.scheduler.authkey)                                                                                                                                  
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/python2.7/multiprocessing/connection.py", line 165, in Client                                                                                                                     
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     family = family or address_type(address)                                                                                                                                                       
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:   File "/usr/lib/python2.7/multiprocessing/connection.py", line 111, in address_type                                                                                                               
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR:     raise ValueError('address type of %r unrecognized' % address)                                                                                                                                  
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR: ValueError: address type of u'/var/lib/temboard/.tm.socket' unrecognized                                                                                                                           
2019-09-28 12:04:59,282 temboardui[28103]: [web] ERROR: Request failed: 500 address type of u'/var/lib/temboard/.tm.socket' unrecognized.                                                                                                                  
2019-09-28 12:04:59,283 temboardui[28103]: [access] ERROR: 500 POST /monitoring/collector (192.168.74.150) 89.21ms     
```

temboard-agent.log :
```
2019-09-28 12:04:58,656 temboardagent[21514]: [monitoring] DEBUG: Starting sender
2019-09-28 12:04:59,160 temboardagent[21514]: [monitoring] DEBUG: Trying to send data to collector
2019-09-28 12:04:59,161 temboardagent[21514]: [monitoring] DEBUG: https://pegase:3001/monitoring/collector
2019-09-28 12:04:59,162 temboardagent[21514]: [monitoring] DEBUG: {"instances": [{"available": true, "tablespaces": null, "dbnames": [], "version_num": 90615, "database": "postgres", "standby": false, "hostname": "pegase.dalibo.net", "instance": "9.6/defo", "host": "/run/postgresql", "version": "9.6.15", "user": "postgres", "data_directory": "/var/lib/postgresql/9.6/defo", "local_name": "9.6/defo", "port": 9601, "sysuser": "postgres", "max_connections": "100"}], "version": "4.1", "data": {"memory": [{"mem_used":     ... and so on

2019-09-28 12:04:59,284 temboardagent[21514]: [monitoring] ERROR: Failed to send data to collector: address type of u'/var/lib/temboard/.tm.socket' unrecognized

2019-09-28 12:04:59,284 temboardagent[21514]: [monitoring] ERROR: You should find details in temBoard UI logs.
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR: Failed to send data to collector.
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR: Traceback (most recent call last):
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 888, in exec_worker
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 1051, in wrapper
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 257, in monitoring_sender_worker
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR:     raise Exception("Failed to send data to collector.")
2019-09-28 12:04:59,285 temboardagent[21514]: [taskmanager] ERROR: Exception: Failed to send data to collector.
2019-09-28 12:04:59,358 temboardagent[16481]: [taskmanager] DEBUG: Job monitoring_sender is dead
2019-09-28 12:04:59,359 temboardagent[16481]: [taskmanager] DEBUG: Job output : {'content': Exception('Failed to send data to collector.',), 'type': (6,)}
2019-09-28 12:04:59,361 temboardagent[16482]: [taskmanager] DEBUG: Received Message={'content': {'status': 32, 'output': Exception('Failed to send data to collector.',), 'stop_datetime': datetime.datetime(2019, 9, 28, 10, 4, 59, 360131), 'task_id': 'monitoring_sender'}, 'type': 1}
```

**Comment by bersace** [comment]
Closing stale issue. Please reopen if you have updates.

**Comment by Krysztophe** [comment]
Cannot reproduce anyway.
