### ISSUE TITLE
Error with unpack on PG11

### ISSUE THREAD

**Issue by madtibo** [dalibo/temboard-agent#375]
Hello,

When I select the instance in UI, I have the following error on PG11 (no problem on PG12):
```
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR: need more than 1 value to unpack
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR: Traceback (most recent call last):
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 903, in exec_worker
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 1066, in wrapper
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 222, in monitoring_sender_worker
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:     msg = q.shift(delete=False)
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/queue.py", line 197, in shift
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:     message = self.parse_row_message(row_message)
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/queue.py", line 180, in parse_row_message
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR:     (id, sign) = row_message[:26].split(":")
2019-11-15 15:00:00,518 temboardagent[30728]: [taskmanager] ERROR: ValueError: need more than 1 value to unpack
```

Really no idea where it can come from.
Any clue to debug this issue?

**Comment by bersace** [comment]
Closing stale issue. Please reopen if you have this issue with latest release.
