### ISSUE TITLE
Failed to send data to collector

### ISSUE THREAD

**Issue by xroman70** [dalibo/temboard-agent#380]
Hello,
while checking  agent status with:  systemctl status temboard-agent@11-data.service
the following error is shown:

```
Failed to send data to collector.
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/taskmanager.py", line 888, in exec_worker
     res = getattr(sys.modules[module], function)(*args, **kws)
   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/taskmanager.py", line 1051, in wrapper
     return function(app=self.app, *a, **kw)
   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 257...r_worker
     raise Exception("Failed to send data to collector.")
 Exception: Failed to send data to collector.

from UI  temboard.log:
[web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 44, in check_agent_request
[web] ERROR:     key)
[web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 132, in check_agent_key
[web] ERROR:     "in application.instances table." % hostname)
[web] ERROR: Exception: Can't find the instance "test-gt-db-01.prv.apps.io" in application.instances table.
[web] ERROR: Request failed: 500 Can't find the instance "test-gt-db-01.prv.apps.io" in application.instances table..
[access] ERROR: 500 POST /monitoring/collector (172.21.10.205) 3.69ms
[web] ERROR: Unhandled Error:
[web] ERROR: Traceback (most recent call last):
[web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/web.py", line 224, in error_middleware
[web] ERROR:     return func(request, *args)
[web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/web.py", line 379, in json_middleware
[web] ERROR:     return func(request, *args)
[web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/web.py", line 419, in user_middleware
[web] ERROR:     return func(request, *args)
[web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 112, in collector
```

Could you provide recommendation to rectify the error?

**Comment by bersace** [comment]
hi @xroman70 , do you have registered the agent for test-gt-db-01.prv.apps.io on UI ?

**Comment by xroman70** [comment]
Hello Étienne, I've reinstalled the agent with umask 022 (was 027) . No
errors generated since. The case can be closed.

Thank you
