### ISSUE TITLE
Streaming Replication Status Showing as UNDEF

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#382]
Streaming replication on standby is empty and showing as UNDEF...

![image](https://user-images.githubusercontent.com/30243584/73403338-db5be280-42b4-11ea-8350-0ab1130ff81f.png)

Please let me know what details you need. I would prefer to send these via email to keep results confidential.

**Comment by bsislow** [comment]
I see this in the temboard agent log. What does this imply; what password is not being fed?

```
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR: No password supplied
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR: Traceback (most recent call last):
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/probes.py", line 768, in run
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR:     p_conn.connect()
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 847, in connect
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR:     raise error('PGC108', 'FATAL', "No password supplied")
2020-01-29 16:53:03,455 temboardagent[74229]: [probes] ERROR: error: No password supplied
```

**Comment by bsislow** [comment]
this looks to be resolved.
