### ISSUE TITLE
ERROR:  function pg_xlog_location_diff(text, pg_lsn) does not exist at character 8

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#483]
The following keeps repeating in the PostgreSQL log for a standby cluster that we just built out on older PG (9.6) using repmgr 5.1 from 2ndQuadrant:

```
2020-10-11 09:34:46 CDT [15216]: [1-1] user=postgres,db=postgres,app=[unknown],client=[local] ERROR:  function pg_xlog_location_diff(text, pg_lsn) does not exist at character 8
2020-10-11 09:34:46 CDT [15216]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2020-10-11 09:34:46 CDT [15216]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] STATEMENT:  SELECT pg_xlog_location_diff(  '44E/2EBD2450'::TEXT,   pg_last_xlog_replay_location()) AS lsn_diff, NOW() AS datetime
2020-10-11 09:34:46 CDT [15216]: [4-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  could not send data to client: Broken pipe
2020-10-11 09:34:46 CDT [15216]: [5-1] user=postgres,db=postgres,app=[unknown],client=[local] FATAL:  connection to client lost
```

FYI:
```
$ rpm -qa| grep temboard
temboard-agent-6.0-1.el7.noarch
$ psql -V
psql (PostgreSQL) 9.6.15
```

**Comment by bersace** [comment]
Hi @bsislow .

That's odd. https://www.postgresql.org/docs/9.6/functions-admin.html#FUNCTIONS-ADMIN-BACKUP states signature is (location, location).

**Comment by bsislow** [comment]
odd yes... but what do we do?

**Comment by bersace** [comment]
@bsislow do you have errors in temboard-agent logs ?

**Comment by bsislow** [comment]
does this help?

```
2020-10-11 09:53:09,106 temboardagent[19526]: [probes] INFO: Loaded probe: locks
2020-10-11 09:53:09,106 temboardagent[19526]: [probes] INFO: Loaded probe: btree_bloat
2020-10-11 09:53:09,106 temboardagent[19526]: [probes] INFO: Loaded probe: process
2020-10-11 09:53:09,106 temboardagent[19526]: [probes] INFO: Loaded probe: replication_lag
2020-10-11 09:53:09,106 temboardagent[19526]: [probes] INFO: Loaded probe: wal_files
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: blocks
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: replication_connection
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: db_size
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: tblspc_size
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: temp_files_size_delta
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: sessions
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: xacts
2020-10-11 09:53:09,107 temboardagent[19526]: [probes] INFO: Loaded probe: memory
2020-10-11 09:53:09,108 temboardagent[19526]: [probes] INFO: Loaded probe: heap_bloat
2020-10-11 09:53:09,108 temboardagent[19526]: [probes] INFO: Loaded probe: loadavg
2020-10-11 09:53:09,108 temboardagent[19526]: [probes] INFO: Loaded probe: filesystems_size
2020-10-11 09:53:09,108 temboardagent[19526]: [probes] INFO: Loaded probe: cpu
2020-10-11 09:53:09,108 temboardagent[19526]: [probes] INFO: Loaded probe: bgwriter
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR: function pg_xlog_location_diff(text, pg_lsn) does not exist
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR: Traceback (most recent call last):
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/probes.py", line 820, in run
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:     ") AS lsn_diff, NOW() AS datetime".format(xlogpos=xlogpos)
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 909, in execute
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:     self.get_nb_rows()
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 1002, in get_nb_rows
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:     for _ in self.get_rows():
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 995, in get_rows
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:     self._check_message_error(message)
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 710, in _check_message_error
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR:     raise error(code, typ, msg)
2020-10-11 09:53:09,717 temboardagent[19526]: [probes] ERROR: error: function pg_xlog_location_diff(text, pg_lsn) does not exist
```

**Comment by bersace** [comment]
does agent crash ?

**Comment by bsislow** [comment]
no, but the postgres log does get flooded with these alerts.

**Comment by bersace** [comment]
@bsislow thanks. We'll try to reproduce and produce a fix. In the meantime, you can disable the `replication_lag` probe in temboard-agent.conf.d by listing all probes except `replication_lag`.

```
# Available probes: bgwriter,blocks,btree_bloat,cpu,db_size,filesystems_size,heap_bloat,loadavg,locks,memory,process,replication_connection,replication_lag,sessions,tblspc_size,temp_files_size_delta,wal_files,xacts
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = bgwriter,blocks,btree_bloat,cpu,db_size,filesystems_size,heap_bloat,loadavg,locks,memory,process,replication_connection,sessions,tblspc_size,temp_files_size_delta,wal_files,xacts
```

**Comment by bsislow** [comment]
this is what we have under `/etc/temboard-agent/9.6/pg45221`:

```
# Available probes: locks,process,db_size,tblspc_size,sessions,blocks,xacts,replication,loadavg,filesystems_size,cpu,bgwriter,memory,wal_files
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = *
```

... so, i don't even see replication_lag in the list.

**Comment by bersace** [comment]
> this is what we have under `/etc/temboard-agent/9.6/pg45221`:
> 
> ```
> # Available probes: locks,process,db_size,tblspc_size,sessions,blocks,xacts,replication,loadavg,filesystems_size,cpu,bgwriter,memory,wal_files
> # when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
> probes = *
> ```
> 
> ... so, i don't even see replication_lag in the list.

This list is just a comment. It misses probes. The comment has been updated in 7.0. Thus the probes value I wrote for you at https://github.com/dalibo/temboard-agent/issues/483#issuecomment-707121647 . Can you give it a try ?

**Comment by bersace** [comment]
Hi @bsislow I reproduced and proposed a fix in #493 !

**Comment by bsislow** [comment]
thanks!

**Comment by pgiraud** [comment]
@bsislow A new version 7.2 of the agent has been release yesterday. It includes the fix for the issue you reported. Please install this new version and change the configuration back to original.

**Comment by bsislow** [comment]
this has been fixed, thank you for the quick response!
