### ISSUE TITLE
After Upgrade to v7 Agent and Enabling statements Plugin - "Error while fetching statements from instance: Internal error."

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#486]
after upgrading and activating the `statements` plugin, we are receiving the following:

![image](https://user-images.githubusercontent.com/30243584/95785327-29761200-0c9b-11eb-8a67-a68ed81e53c2.png)

here's the relevant error in the temboard agent log file; i replaced the actual database name with "thedatabase":

```
2020-10-12 14:53:58,538 temboardagent[4757]: [probes] INFO: Loaded probe: heap_bloat
2020-10-12 14:53:58,538 temboardagent[4757]: [probes] INFO: Loaded probe: loadavg
2020-10-12 14:53:58,538 temboardagent[4757]: [probes] INFO: Loaded probe: filesystems_size
2020-10-12 14:53:58,539 temboardagent[4757]: [probes] INFO: Loaded probe: cpu
2020-10-12 14:53:58,539 temboardagent[4757]: [probes] INFO: Loaded probe: bgwriter
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR: thedatabase
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR: Traceback (most recent call last):
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 132, in response
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR:     (code, message) = self.route_request()
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 286, in route_request
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR:     return (200, func(http_context, self.app))
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/statements/__init__.py", line 31, in get_statements
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR:     assert dbname == "postgres", dbname
2020-10-12 14:54:19,235 temboardagent[12368]: [httpd] ERROR: AssertionError: thedatabase
2020-10-12 14:54:19,236 temboardagent[12368]: [httpd] ERROR: Internal error
2020-10-12 14:54:19,237 temboardagent[12368]: [httpd] INFO: client: pgstmb001v.prd.chi.accertify.net request: "GET /statements?key=9ae98817c598c1f6f34b110e80567b60 HTTP/1.1" 500 - 2.26ms
2020-10-12 14:54:23,444 temboardagent[12368]: [api] INFO: Starting discovery.
2020-10-12 14:54:23,466 temboardagent[12368]: [api] INFO: Discovery done.
2020-10-12 14:54:23,467 temboardagent[12368]: [httpd] INFO: client: pgstmb001v.prd.chi.accertify.net request: "GET /discover HTTP/1.1" 200 - 22.89ms
2020-10-12 14:54:23,523 temboardagent[12368]: [httpd] INFO: client: pgstmb001v.prd.chi.accertify.net request: "GET /monitoring/history?key=9ae98817c598c1f6f34b110e80567b60&limit=100&start=2
```

and here's our statements section in the `temboard-agent.conf` file:

```
[statements]
# Statements plugin part.
# DB name hosting pg_stat_statements view (the one where the extension has
# been created with "CREATE EXTENSION")
dbname = thedatabase
```

**Comment by pgiraud** [comment]
Thanks for the report. That's indeed a bug.
Do you have a "postgres" database on this instance? If so, can you create the extension on this database and change the configuration accordingly?
If not, we'll do our best to fix this annoying issue as quickly as possible.

**Comment by bsislow** [comment]
yes, i've modified it to `postgres`. however, there's no activity under that database. this is why we create the extension under our application databases. i'm sure this is obvious to you - and we'll await your update.

**Comment by pgiraud** [comment]
@bsislow FYI it doesn't really matter where the `pg_stat_statements` extension is created. It collects information for all the databases on the server.
However there was a bug in temboard preventing users to actually use a different database than the default one (ie. `postgres`).
This will be fixed in next minor release.

**Comment by bsislow** [comment]
noted, just figured this out 👍 
we will use `postgres` for now

**Comment by bsislow** [comment]
please reopen this... we are getting the same issue even with:

```
[statements]
# Statements plugin part.
# DB name hosting pg_stat_statements view (the one where the extension has
# been created with "CREATE EXTENSION")
dbname = postgres
```

**Comment by pgiraud** [comment]
It looks like the message is different. Do you have anything in the logs? Please check on both sides.

**Comment by bsislow** [comment]
i emailed you a response...

**Comment by pgiraud** [comment]
Thanks.
The "not found URL" most probably means that the agent doesn't know anything about the plugin statements.

Can you please ensure that the "statements" plugin is activated on the agent side (ie. loaded via the config file) ?
See: https://temboard.readthedocs.io/projects/agent/en/v7/upgrade.html#x-to-7-0
