### ISSUE TITLE
Error while fetching statements from instance: pg_stat_statements not enabled on database postgres

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#496]
after enabling the "statements" plugin, we are getting the error below on some instances.

`pg_stat_statements` already exists in the `postgres` database on all of these instances.

the `plugin` `statements` has been enabled on these instances.

![image](https://user-images.githubusercontent.com/30243584/97018914-4e794900-1515-11eb-9217-6c122c56a56b.png)

this is the error in the temboard agent log:

```
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR: {'error': 'pg_stat_statements not enabled on database postgres'}
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR: Traceback (most recent call last):
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 132, in response
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR:     (code, message) = self.route_request()
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 286, in route_request
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR:     return (200, func(http_context, self.app))
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/statements/__init__.py", line 44, in get_statements
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR:     404, "pg_stat_statements not enabled on database %s" % dbname
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR: HTTPError: pg_stat_statements not enabled on database postgres
2020-10-23 09:51:21,475 temboardagent[15567]: [httpd] ERROR: {'error': 'pg_stat_statements not enabled on database postgres'}
2020-10-23 09:51:21,476 temboardagent[15567]: [httpd] INFO: client: pgstmb001v.prd.chi.accertify.net request: "GET /statements?key=8a1b4bc73d4055e1d1289c09e3ddb52f HTTP/1.1" 404 - 3.10ms
```

i am not sure what is missing - if anything.

i can send specifics via email; just provide the address to send to.

**Comment by pgiraud** [comment]
The `pg_stat_statements` extension has to be loaded via `shared_preload_libraries` in postgresql conf.

Then you also need to do `CREATE EXTENSION pg_stat_statements;`.

What does the following SQL command return in psql on the instance?
```
SELECT                                         
  rolname,                                     
  datname,                                     
  pgss.*                                       
FROM pg_stat_statements pgss                   
JOIN pg_authid ON pgss.userid = pg_authid.oid  
JOIN pg_database ON pgss.dbid = pg_database.oid;
```

**Comment by bsislow** [comment]
that's the one part i missed; you can close this. we did not load it via `shared_preload_libaries`. so many steps to remember 👍 

thanks!

**Comment by bsislow** [comment]
actually, we are still getting that error even after adding `pg_stat_statements` to `shared_preload_libraries` and bouncing the instance _and_ temboard agent.

fyi - lots of output; trimmed this:

```
postgres=# \c
You are now connected to database "postgres" as user "postgres".
postgres=# SELECT
  rolname,
  datname,
  pgss.*
FROM pg_stat_statements pgss
JOIN pg_authid ON pgss.userid = pg_authid.oid
JOIN pg_database ON pgss.dbid = pg_database.oid;
 rolname  | datname  | userid | dbid  |       queryid        |

                                                                                                                                                                           query


                                                                                                 | calls |      total_time      |       min_time        |       max_time       |       mean_t
ime        |      stddev_time       | rows  | shared_blks_hit | shared_blks_read | shared_blks_dirtied | shared_blks_written | local_blks_hit | local_blks_read | local_blks_dirtied | local_
blks_written | temp_blks_read | temp_blks_written | blk_read_time | blk_write_time
----------+----------+--------+-------+----------------------+-------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------+-------+----------------------+-----------------------+----------------------+-------------
-----------+------------------------+-------+-----------------+------------------+---------------------+---------------------+----------------+-----------------+--------------------+-------
-------------+----------------+-------------------+---------------+----------------
 airflow  | airflow  |  16391 | 16392 | -1953580890503468778 | SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_instance.dag
_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_
date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instance.hostname AS task_instan
ce_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.queue AS task_instance_q
ueue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, task_instance
.pid AS task_instance_pid, task_instance.executor_config AS task_instance_executor_config       +|   123 |    7.391163000000005 |              0.023706 |             0.276721 |   0.06009075
6097560975 |   0.030029792716686845 |   123 |             516 |                0 |                   3 |                   0 |              0 |               0 |                  0 |
           0 |              0 |                 0 |             0 |              0
          |          |        |       |                      | FROM task_instance




                                                                                                +|       |                      |                       |                      |
           |                        |       |                 |                  |                     |                     |                |                 |                    |
             |                |                   |               |
          |          |        |       |                      | WHERE task_instance.dag_id = $1 AND task_instance.task_id = $2 AND task_instance.execution_date = $3::timestamptz




                                                                                                +|       |                      |                       |                      |
           |                        |       |                 |                  |                     |                     |                |                 |                    |
             |                |                   |               |
          |          |        |       |                      |  LIMIT $4
...
...
```

**Comment by pgiraud** [comment]
Is the version of the instance you are monitoring 9.5 or below?
The statements plugin is only compatible with PG >= 9.6.

**Comment by bsislow** [comment]
we're on 12.3...

```
$ psql -V
psql (PostgreSQL) 12.3
```

**Comment by pgiraud** [comment]
@bsislow is the error you are getting now is exactly the same or did the error message change?

**Comment by bsislow** [comment]
this is the current error; the one i re-opened this case with:

![image](https://user-images.githubusercontent.com/30243584/97310090-d8385780-1830-11eb-9f82-32e88e125e39.png)

**Comment by bsislow** [comment]
this was an issue on our end; we had to issue the following as `pg_stat_statements` is installed under a specific schema and the `temboard` user is used for monitoring connections...

```
grant usage on schema dbaadmin to temboard ;
alter user temboard set search_path='dbaadmin';
```
