### ISSUE TITLE
(v7.2) Installation fails on Ubuntu 20.04 focal : Depends: python-psycopg2 but it is not installable

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard-agent#498]
I have the problem on 2 computers.  `python-psycopg2` is unavailable (but `python3-psycopg2` exists). 

Perhaps a consequence of #477?

```bash
# apt install temboard-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 temboard-agent : Depends: python-psycopg2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

```
# apt-cache policy temboard-agent
temboard-agent:
  Installed: (none)
  Candidate: 7.2-0dlb1buster1
  Version table:
     7.2-0dlb1stretch1 -1
        100 /var/lib/dpkg/status
     7.2-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs buster-dalibo/main all Packages
     7.1-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs buster-dalibo/main all Packages
     7.0-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs buster-dalibo/main all Packages
     6.0-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs buster-dalibo/main all Packages
```

```
root@monolithe:/etc/apt/sources.list.d# apt-cache policy  psycopg2
N: Unable to locate package psycopg2
root@monolithe:/etc/apt/sources.list.d# apt-cache search psycopg2
python-psycopg2-doc - Python module for PostgreSQL (documentation package)
python3-psycopg2 - Python 3 module for PostgreSQL
python3-psycopg2-dbg - Python 3 module for PostgreSQL (debug extension)
python3-psycogreen - psycopg2 integration with coroutine libraries
```

**Comment by dlax** [comment]
We need to upgrade the Debian package to python3, as we did for the RPM one recently, at least for recent Debian-based distributions.

**Comment by pgiraud** [comment]
@Krysztophe we released new packages for Debian last week. Can you please have them a try?

**Comment by Krysztophe** [comment]
The installation works now, but it fails at start (same for 3 agents on my 2 computers). Shall I make another issue?

```
root@monolithe:/var/log/temboard-agent# systemctl status temboard-agent@12-huge
● temboard-agent@12-huge.service - PostgreSQL Remote Control Agent 12/huge
     Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-11-16 20:40:04 CET; 3s ago
    Process: 3381306 ExecStart=/usr/bin/env SYSTEMD=1 temboard-agent -c /etc/temboard-agent/12/huge/temboard-agent.conf (code=exited, status=1/FAILURE)
   Main PID: 3381306 (code=exited, status=1/FAILURE)

nov. 16 20:40:04 monolithe systemd[1]: Started PostgreSQL Remote Control Agent 12/huge.
nov. 16 20:40:04 monolithe env[3381306]: Traceback (most recent call last):
nov. 16 20:40:04 monolithe env[3381306]:   File "/usr/bin/temboard-agent", line 5, in <module>
nov. 16 20:40:04 monolithe env[3381306]:     from temboardagent.scripts.agent import main
nov. 16 20:40:04 monolithe env[3381306]: ModuleNotFoundError: No module named 'temboardagent'
nov. 16 20:40:04 monolithe systemd[1]: temboard-agent@12-huge.service: Main process exited, code=exited, status=1/FAILURE
nov. 16 20:40:04 monolithe systemd[1]: temboard-agent@12-huge.service: Failed with result 'exit-code'.
```
```
$ sudo apt-cache policy temboard-agent
[sudo] Mot de passe de christ : 
temboard-agent:
  Installé : 7.3-0dlb1buster1
  Candidat : 7.3-0dlb1buster1
 Table de version :
 *** 7.3-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs buster-dalibo/main all Packages
        100 /var/lib/dpkg/status
     7.2-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs buster-dalibo/main all Packages
...
```
```
~$ apt-cache show temboard-agent
Package: temboard-agent
Priority: extra
Section: database
Installed-Size: 666
Maintainer: Pierre Giraud <pierre.giraud@dalibo.com>
Architecture: all
Version: 7.3-0dlb1buster1
Depends: python3-pkg-resources, ssl-cert, python3-psycopg2, python3
Filename: pool/main/t/temboard-agent/temboard-agent_7.3-0dlb1buster1_all.deb
Size: 216456
MD5sum: 402c83898a33e7fa6caf92d7bce95ed3
SHA1: 5f6b0f3f799a6233b8831daa7a099c97a3074c06
SHA256: 42fd27822d4a4d46d2ed2aca9f50a961377d34d14483e07f008cc80ac5ba73f7
SHA512: 7a96fcc4be4f8f0cdb2621661d9c42acbe737a76daf656ea7ffccbd14cf50d5c06ba3b54f4f86b7b86daed65069c0b14792e8bffea4445b04c21abb3321220c5
Description: PostgreSQL Remote Control Agent
Description-md5: 4ea379885291c2e1fef995ecccf8debd
License: PostgreSQL
Vendor: @32925ae46078
Homepage: http://temboard.io/
```

**Comment by pgiraud** [comment]
Let's continue here.
What does the following command show?
```
temboard-agent --version
```

**Comment by Krysztophe** [comment]
```
$ temboard-agent --version
Traceback (most recent call last):
  File "/usr/bin/temboard-agent", line 5, in <module>
    from temboardagent.scripts.agent import main
ModuleNotFoundError: No module named 'temboardagent'
```

**Comment by pgiraud** [comment]
A new version 7.4 of the agent has been released. Can you please try to install it and run it?

**Comment by Krysztophe** [comment]
That's much better. No error, and the .log and .db files are filled with activity. My temboard instances are still stuck (due to https://github.com/dalibo/temboard/issues/876) so I cannot check further, but at 1st sight this problem seems solved. Thanks!

```
$ sudo systemctl status temboard-agent@12-huge.service
● temboard-agent@12-huge.service - PostgreSQL Remote Control Agent 12/huge
     Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-11-18 11:30:32 CET; 1s ago
   Main PID: 4029497 (temboard-agent)
      Tasks: 3 (limit: 57358)
     Memory: 34.1M
     CGroup: /system.slice/system-temboard\x2dagent.slice/temboard-agent@12-huge.service
             ├─4029497 temboard-agent: 12/huge: main process
             ├─4029507 temboard-agent: 12/huge: worker pool
             └─4029508 temboard-agent: 12/huge: scheduler

nov. 18 11:30:33 monolithe env[4029497]: {'http_method': 'DELETE', 'root': b'maintenance', 'path': b'/maintenance/reindex/(^[0-9a-f]{8}$)', 'splitpath': [b'maintenance', b'reinde>
nov. 18 11:30:33 monolithe env[4029497]: {'http_method': 'GET', 'root': b'maintenance', 'path': b'/maintenance/reindex/scheduled', 'splitpath': [b'maintenance', b'reindex', b'sch>
nov. 18 11:30:33 monolithe env[4029497]: Starting <temboardagent.httpd.HTTPDService object at 0x7fdf4566f970>.
nov. 18 11:30:33 monolithe env[4029507]: Starting <temboardagent.toolkit.taskmanager.WorkerPoolService object at 0x7fdf458baac0>.
nov. 18 11:30:33 monolithe env[4029507]: Entering <temboardagent.toolkit.taskmanager.WorkerPoolService object at 0x7fdf458baac0> loop.
nov. 18 11:30:33 monolithe env[4029508]: Starting <temboardagent.toolkit.taskmanager.SchedulerService object at 0x7fdf458baf10>.
nov. 18 11:30:33 monolithe env[4029508]: Entering <temboardagent.toolkit.taskmanager.SchedulerService object at 0x7fdf458baf10> loop.
nov. 18 11:30:33 monolithe env[4029497]: Using SSL key /etc/ssl/private/ssl-cert-snakeoil.key.
nov. 18 11:30:33 monolithe env[4029497]: Using SSL certificate /etc/ssl/certs/ssl-cert-snakeoil.pem.
nov. 18 11:30:33 monolithe env[4029497]: Entering <temboardagent.httpd.HTTPDService object at 0x7fdf4566f970> loop.
```

**Comment by Krysztophe** [comment]
This problem does not occur anymore with temboard-agent 7.6. It works, now.
