### ISSUE TITLE
Error while fetching statements from instance: 'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard-agent#513]
Dear temBoard team

On a PostgreSQL 10.15 Instance, we do get the following error when clicking on the Statements section in temBoard.

Error while fetching statements from instance: 'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)

![image](https://user-images.githubusercontent.com/54099545/103994222-f9091b80-5196-11eb-80ad-23a361a25a45.png)

What is different in this instance, is that we have two databases with a different encoding. LATIN1 in our case.

```
(postgres@[local]:55021)[mydb01]> \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 mydb01 | myuser01| LATIN1   | C           | C           |
 mydb02     | myuser02   | LATIN1   | C           | C           |
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
```

On all other instances where we run UTF8 it works perfectly.

I think that you can reproduce this issue easily by creating a database with encoding 'LATIN1'.

```
CREATE DATABASE mydb ENCODING 'LATIN1' TEMPLATE template0 LC_COLLATE='C' LC_CTYPE='C';
\c mydb
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
```

Best regards
William

**Comment by wsescu** [comment]
Dear @dlax 

attached you will find a trace from the agent log:

```
2021-01-11 11:24:53,747 temboardagent[21132]: [statements] ERROR: Failed to get pg_stat_statements data on database postgres: 'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR: {'error': "'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)"}
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR: Traceback (most recent call last):
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/statements/__init__.py", line 35, in get_statements
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:     data = list(conn.query(query))
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/postgres.py", line 41, in query
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:     for row in cur:
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:   File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 118, in __iter__
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:     yield next(res)
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR: During handling of the above exception, another exception occurred:
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR: Traceback (most recent call last):
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 131, in response
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:     (code, message) = self.route_request()
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 286, in route_request
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:     return (200, func(http_context, self.app))
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/statements/__init__.py", line 50, in get_statements
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR:     raise HTTPError(500, e)
2021-01-11 11:24:53,748 temboardagent[21132]: [httpd] ERROR: temboardagent.errors.HTTPError: 'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)
2021-01-11 11:24:53,749 temboardagent[21132]: [httpd] ERROR: {'error': "'ascii' codec can't decode byte 0xc3 in position 3210: ordinal not in range(128)"}
```

Cheers
William

**Comment by pgiraud** [comment]
In order to test @dlax fix, I need to reproduce the issue you're facing. So far, I wasn't able to get any error.
Here's what I've done :
 - create a new database with LATIN1 encoding,
 - drop extension `pg_stat_statements` on postgres database,
 - create extension on the new database,
 - change temboard agent configuration (`dbname` parameter) for the statements plugin to use the new database,
 - created some statements by creating new tables and queries in the new database, with some accents in table names and predicates.

Can you please tell us which version of temboard agent is installed?
Also what is the version of python?
On which system are you running the agent?

**Comment by wsescu** [comment]
Dear @pgiraud , dear @dlax 

on the system, where we have the issue with the PostgreSQL 10.15 database with LATIN1, we do have the following versions installed. (See below) In regards to python, we do have version 2 and 3 installed. I think version 3 came automatically when we upgraded to temboard agent 7.4.

```
$ temboard-agent --version
 INFO: Starting temboard-agent 7.5.
7.5

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)

$ uname -a
Linux hostname 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

$ python -V
Python 2.7.5

$ python3 -V
Python 3.6.8
```

Cheers
William

**Comment by pgiraud** [comment]
Can you please show what the result of the following SQL statement look like? Please un it on `postgres` database (or the database configured in `dbname` in the agent config for the statements plugin).
``` SQL
SELECT 
  regexp_replace(substr(query, 0, 150), E'[\\n\\r]+', ' ', 'g' )
FROM pg_stat_statements pgss
JOIN pg_database pgd
ON pgss.dbid = pgd.oid
WHERE datname = 'mydb01';
```
If for security reasons you don't want this to be on github, please send it to pierre(dot)giraud(at)dalibo(dot).com.

**Comment by wsescu** [comment]
Dear @pgiraud 
have send you the information via Email.
Cheers
William

**Comment by wsescu** [comment]
Dear @pgiraud 

it looks like that resetting the stats fixed the issue. 

```
(postgres@[local]:55021)[postgres]> SELECT pg_stat_statements_reset();
 pg_stat_statements_reset
--------------------------

(1 row)

(postgres@[local]:55021)[postgres]>
```

Cheers
William

**Comment by pgiraud** [comment]
Calling `pg_stat_statements_reset` clears the statements data. So the encoding issue disapears at the same time. At least temporarily, until a query with special characters is executed again.
Unfortunately this doesn't help us for finding the issue origin.

**Comment by pgiraud** [comment]
I'm closing this issue. Please reopen if you facing the problem again.
