### ISSUE TITLE
ERROR: invalid dsn: invalid connection option "passfile"

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard-agent#531]
Dear temBoard team

since the upgrade of the Agent from 7.6 to 7.7 I do get the following error in the Agent log file:

```
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR: invalid dsn: invalid connection option "passfile"
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR: Traceback (most recent call last):
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py", line 788, in run
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR:     dsn, connection_factory=PhysicalReplicationConnection
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR:   File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 129, in connect
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR:     dsn = _ext.make_dsn(dsn, **kwargs)
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR:   File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 155, in make_dsn
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR:     parse_dsn(dsn)
2021-06-02 08:25:23,501 temboardagent[30622]: [probes] ERROR: psycopg2.ProgrammingError: invalid dsn: invalid connection option "passfile"
```

Could you please help to fix this issue?

Cheers
William

**Comment by bersace** [comment]
Hi @wsescu , can you share with us a redacted version of the unsupported DSN ?

**Comment by wsescu** [comment]
Dear @bersace 

attached you will find the contents on the temboard-agent.conf file.

```
$ cat /etc/temboard-agent/12/pg55000/temboard-agent.conf

#
# Configuration file generated by /usr/share/temboard-agent/auto_configure.sh.
#

[temboard]
home = /var/lib/temboard-agent/12/pg55000
hostname = host01.example.ch
port = 44000
ssl_cert_file = /etc/pki/tls/certs/temboard-agent-12-pg55000.pem
ssl_key_file = /etc/pki/tls/private/temboard-agent-12-pg55000.key
key = ecd7a08bad3edefdbd8b52ce28173e88

[logging]
method = file
destination = /var/log/temboard-agent/12-pg55000.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = DEBUG

[postgresql]
host = /tmp
port = 55000
user = postgres
dbname = postgres
password = ******************
instance = 12/pg55000

[administration]
pg_ctl = '/app/lib/postgres/pgproduct/pg-12.6/bin/pg_ctl %s -D /app/lib/postgres/pgdata/12/PGXE01B'

[monitoring]
collector_url = https://temboard.example.ch:8888/monitoring/collector
dbnames = *
scheduler_interval = 300
# probes = locks,process,db_size,tblspc_size,sessions,blocks,xacts,replication,loadavg,filesystems_size,cpu,bgwriter,memory,wal_files
# probes = locks,process,db_size,tblspc_size,sessions,blocks,xacts,loadavg,filesystems_size,cpu,bgwriter,memory
probes = *
```

Cheers
William

**Comment by wsescu** [comment]
The instance where I get the "invalid dsn" error is a Standby which is attached to a Primary and perfectly in sync.

**Comment by bersace** [comment]
@wsescu yes, that looks like the DSN as configured in standby `primary_conn`. Can you share this one ?

**Comment by wsescu** [comment]
Sure. Attached is the primary_conninfo. 

```
$ cat postgresql.auto.conf
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
recovery_target_timeline = 'latest'
primary_conninfo = 'user=repmgr connect_timeout=2 host=host00 port=55000 application_name=pgx passfile=''/home/postgres/.pgpass'''
primary_slot_name = 'repmgr_slot_550002'
```

**Comment by orgrim** [comment]
Hello,

`"invalid dsn: invalid connection option "passfile""` is a message from libpq. Under the hood, psycopg2 uses libpq in its `parse_dsn()` function.

This means that your installation of psycopg2 is linked to a libpq older than PostgreSQL 10, where the passfile keyword was introduced. Could you please check:

* look for the psycopg shared library: it should be similar `_psycopg.cpython-36m-x86_64-linux-gnu.so` in `/usr/lib64/python3.6/site-packages/psycopg2/` in your context.
* run `ldd` on it to find the path of the `libpq.so.5` library

Regards

**Comment by wsescu** [comment]
Hello @orgrim 

indeed. It is linked to libpq.so.5.5

```
$ cd /usr/lib64/python3.6/site-packages/psycopg2/
$ ldd _psycopg.cpython-36m-x86_64-linux-gnu.so | grep libpq
        libpq.so.5 => /lib64/libpq.so.5 (0x00002b464425e000)
$ ls -l /lib64/libpq.so.5
lrwxrwxrwx. 1 root root 12 Jul  7  2020 /lib64/libpq.so.5 -> libpq.so.5.5
$ ls -l /lib64/libpq.so.5.5
-rwxr-xr-x. 1 root root 197544 Feb 24  2020 /lib64/libpq.so.5.5
```

Should I change the link to libpq.so.5.12 which I have in a different directory.

Cheers
William

**Comment by orgrim** [comment]
Hello,

You could do that, but it can have side effects. It would be better to upgrade your psycopg2 installation to use a newer version of libpq.

Are you using RPM packages from yum.postgresql.org? If yes, it would be better to use their package: `python3-psycopg2`.

Regards

**Comment by wsescu** [comment]
Dear @orgrim 

thanks a lot for your help. We are using the standard Red Hat 7 repository, and we compile PostgreSQL ourselfs.
I need to figure out a way, how to implement a more up2date copy of python3-psycopg2

Cheers
William

**Comment by wsescu** [comment]
Is there not a way, how I can tell the temboard agent where to find the latest libpq.so? Some kind of LD_LIBRARY_PATH variable, or alike. By introducing a new yum.postgresql.org repository, I end up with too many package conflicts.

**Comment by orgrim** [comment]
Then you can compile psycopg2 as well. The compilation uses `pg_config` so you can point the proper libpq to the build process of psycopg2 by ensuring it used first in your PATH.

**Comment by wsescu** [comment]
Dear @orgrim 

I do have the same issue on Red Hat 8, where I do have a far more recent libpq and pyhton3 is there per default.

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)
$ uname -a
Linux host01 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Wed Feb 3 03:12:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

$ ldd /usr/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so | grep libpq
        libpq.so.5 => /lib64/libpq.so.5 (0x000014ef0d124000)
$ ls -l /lib64/libpq.so.5
lrwxrwxrwx. 1 root root 13 Dec  1  2020 /lib64/libpq.so.5 -> libpq.so.5.12
$ ls -l /lib64/libpq.so.5.12
-rwxr-xr-x. 1 root root 332608 Dec  1  2020 /lib64/libpq.so.5.12


2021-06-07 14:52:38,583 temboardagent[2030906]: [probes] ERROR:   File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 155, in make_dsn
2021-06-07 14:52:38,583 temboardagent[2030906]: [probes] ERROR:     parse_dsn(dsn)
2021-06-07 14:52:38,583 temboardagent[2030906]: [probes] ERROR: psycopg2.ProgrammingError: invalid dsn: missing "=" after "/home/postgres/.pgpass''" in connection info string
2021-06-07 14:52:38,597 temboardagent[2030906]: [probes] ERROR: invalid dsn: missing "=" after "/home/postgres/.pgpass''" in connection info string
2021-06-07 14:52:38,597 temboardagent[2030906]: [probes] ERROR: Traceback (most recent call last):
2021-06-07 14:52:38,597 temboardagent[2030906]: [probes] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py", line 865, in run
2021-06-07 14:52:38,597 temboardagent[2030906]: [probes] ERROR:     dsn = parse_dsn(get_primary_conninfo(conn))
2021-06-07 14:52:38,597 temboardagent[2030906]: [probes] ERROR: psycopg2.ProgrammingError: invalid dsn: missing "=" after "/home/postgres/.pgpass''" in connection info string
```

Looks like that the temBoard Agent does not like the passfile=''/home/postgres/.pgpass'' syntax. Please note that these are not double quotes. These a 2 single quotes.

Cheers
William

**Comment by wsescu** [comment]
After removing the single quotes from the passfile parameter, from 

```
$ cat postgresql.auto.conf.20210607a
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
primary_conninfo = 'host=host00 port=55041 user=repmgr application_name=h51lya0 connect_timeout=2 passfile=''/home/postgres/.pgpass'''
recovery_target_timeline = 'latest'
```

to:

```
$ cat postgresql.auto.conf
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
primary_conninfo = 'host=host00 port=55041 user=repmgr application_name=h51lya0 connect_timeout=2 passfile=/home/postgres/.pgpass'
recovery_target_timeline = 'latest'
```

it works.

**Comment by orgrim** [comment]
Hello,

Yes, the probe does not process the value of primary_conninfo, it uses quote_literal() on it to get the same result as reading recovery.conf contents on pre-12 versions.

It should clean what comes from recovery.conf and not use quote_literal() strating from 12.

Regards

**Comment by orgrim** [comment]
@wsescu Would you mind checking the patch to see if it solves the issue?

Regards

**Comment by wsescu** [comment]
Sure. If you could build me a rpm package for RHEL7 and RHEL8, then I can test both.

**Comment by pgiraud** [comment]
RPMs built with the patch were generated and sent to @wsescu for testing.

**Comment by wsescu** [comment]
Hello @pgiraud 

I have tested both RPM's. On RHEL8 with passfile=''/home/postgres/.pgpass'' it works perfectly. 😊

On RHEL7 with passfile=''/home/postgres/.pgpass'' (RHEL7 is shipped with quite old Postgres libs) I do get the following error.

```
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR: invalid dsn: invalid connection option "passfile"
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR: Traceback (most recent call last):
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py", line 794, in run
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR:     dsn, connection_factory=PhysicalReplicationConnection
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR:   File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 129, in connect
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR:     dsn = _ext.make_dsn(dsn, **kwargs)
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR:   File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 155, in make_dsn
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR:     parse_dsn(dsn)
2021-06-09 08:08:16,298 temboardagent[29969]: [probes] ERROR: psycopg2.ProgrammingError: invalid dsn: invalid connection option "passfile"
2021-06-09 08:08:16,326 temboardagent[29969]: [probes] ERROR: invalid dsn: invalid connection option "passfile"
2021-06-09 08:08:16,326 temboardagent[29969]: [probes] ERROR: Traceback (most recent call last):
2021-06-09 08:08:16,326 temboardagent[29969]: [probes] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py", line 871, in run
2021-06-09 08:08:16,326 temboardagent[29969]: [probes] ERROR:     dsn = parse_dsn(get_primary_conninfo(conn))
2021-06-09 08:08:16,326 temboardagent[29969]: [probes] ERROR: psycopg2.ProgrammingError: invalid dsn: invalid connection option "passfile"
```

However, if I add the **LD_LIBRARY_PATH** to the Agent Service file, to point to more recent libs, then it works fine.

```
$ cat /usr/lib/systemd/system/temboard-agent@.service
[Unit]
Description=PostgreSQL Remote Control Agent %I
After=network.target postgresql@%i.service
AssertPathExists=/etc/temboard-agent/%I/temboard-agent.conf

[Service]
Type=simple
User=postgres
Group=postgres
Environment="LD_LIBRARY_PATH=/app/lib/postgres/pgproduct/pg-12.6/lib"
ExecStart=/usr/bin/env SYSTEMD=1 temboard-agent -c /etc/temboard-agent/%I/temboard-agent.conf

[Install]
WantedBy=multi-user.target
```

Cheers
William
