### ISSUE TITLE
Streaming Replication is showing as UNDEF for all targets after upgrade to 7.10

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#567]
per the subject, all of our replica targets are showing as UNDEF after an upgrade to 7.10...

![image](https://user-images.githubusercontent.com/30243584/155437154-255c1b5f-c8bc-4a8e-bf21-450c1fbf9e25.png)

i see this repeating in `/var/log/messages`:

```
Feb 23 19:03:43 xxxxxxxx env: Running instance probe replication_connection.
Feb 23 19:03:43 xxxxxxxx env: syntax error at or near "CASE"
Feb 23 19:03:43 xxxxxxxx env: LINE 2: CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS connected
Feb 23 19:03:43 xxxxxxxx env:        ^
Feb 23 19:03:43 xxxxxxxx env: Traceback (most recent call last):
Feb 23 19:03:43 xxxxxxxx env:  File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py", line 859, in run
Feb 23 19:03:43 xxxxxxxx env:    return list(rows)
Feb 23 19:03:43 xxxxxxxx env:  File "/usr/lib/python3.6/site-packages/temboardagent/postgres.py", line 39, in query
Feb 23 19:03:43 xxxxxxxx env:    cur.execute(dedent(query), vars)
Feb 23 19:03:43 xxxxxxxx env:  File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 248, in execute
Feb 23 19:03:43 xxxxxxxx env:    return super(RealDictCursor, self).execute(query, vars)
Feb 23 19:03:43 xxxxxxxx env: psycopg2.errors.SyntaxError: syntax error at or near "CASE"
Feb 23 19:03:43 xxxxxxxx env: LINE 2: CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS connected
Feb 23 19:03:43 xxxxxxxx env:        ^
```

**Comment by bersace** [comment]
UNDEF is "No data". This appears on switchover and is expected.

For the SQL error, what version of PostgreSQL are you running ?

**Comment by bsislow** [comment]
We have 10 replica targets showing UNDEF and none were switched over...

All targets are on 13.2.

They did not show UNDEF before upgrading to 7.10.

**Comment by wsescu** [comment]
There is a Syntax Typo in the file /usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/probes.py

```
SELECT '{p_host}' AS upstream
CASE 
   WHEN COUNT(*) > 0 THEN 1 
   ELSE 0 
END AS connected
FROM pg_stat_wal_receiver
WHERE status='streaming' AND
conninfo LIKE '%host={p_host}%';
```

-- should be ...

```
SELECT '{p_host}' AS upstream,   -- the comma after upstream is missing
CASE 
   WHEN COUNT(*) > 0 THEN 1 
   ELSE 0 
END AS connected
FROM pg_stat_wal_receiver
WHERE status='streaming' AND
conninfo LIKE '%host={p_host}%';
```

**Comment by bersace** [comment]
Ok, I confirm this was introduced in 7.10
